//
//  EcommConstants.swift
//  Do Chat
//
//  Created by Rahul Sharma on 30/07/20.
//  Copyright © 2020 Rahul Sharma. All rights reserved.
//

import Foundation

enum StoreCategories:Int{
    case Ride = 1
    case Grocery = 2
    case Laundry = 5
    case Ecommerce = 8
    case Pharmacy = 6
    case Resturant = 7
    case SuperStore = 10
}

struct EComm{
    //    https://api.shoppd.net/
    static let HostURL = "https://api.besocial.app"
    struct BaseURL {
        static let BaseUrl          = "https://api.besocial.app/"
        static let PrimaryUrl       =  EComm.BaseURL.BaseUrl + "python/"
        static let SecondaryUrl     =  AppConstants.constantURL
        static let PublicIP         = "https://api6.ipify.org"
        static let PromoCode        = "https://promocode-api.shoppd.net/"
        static let stripe           = BaseUrl + "stripe/v1/"
    }
    static let imageUpload = BaseURL.SecondaryUrl + "imageUpload"
    static var storeCategoryID =  "5cc0846e087d924456427975"
    
    struct Urls {
        static let getGhostToken = "https://ghost.shoppd.net/ghost/api/v3/admin/token"
        static let getBlogs = BaseURL.BaseUrl + "ghost/api/v3/admin/posts/"
        struct Food {
            static let getfood  =  BaseURL.PrimaryUrl + "get/food/"
            static let products = getfood + "products/"
            static let stores = getfood + "stores"
            static let addOns =  BaseURL.PrimaryUrl + "product/addons"
            static let filter = BaseURL.PrimaryUrl + "get/store/filters"
            static let favouriteStore = BaseURL.PrimaryUrl + "user/favourite/stores"
            static let searchProducts = BaseURL.PrimaryUrl + "suggestion/food/products/"
            static let viewAllStores = BaseURL.PrimaryUrl + "sellerFilter/"
        }
        
        struct Pedija{
            static let Serices                    = BaseURL.PrimaryUrl + "get/services"
            static let cities                     = BaseURL.SecondaryUrl + "cities"
        }
        
        struct Authorization {
            static let guestSignIn                = BaseURL.SecondaryUrl + "guest/signIn"
            static let zone                       = BaseURL.PrimaryUrl + "zones"
            static let signIn                     = BaseURL.SecondaryUrl + "signIn"
            static let signUp                     = BaseURL.SecondaryUrl + "signUp/New"
            static let resetPassword              = BaseURL.SecondaryUrl + "resetPassword"
            static let forgotPassword             = BaseURL.SecondaryUrl + "forgotPassword"
            static let verifyOtp                  = BaseURL.SecondaryUrl + "customer/verifyOtp"
            static let sendOtp                    = BaseURL.SecondaryUrl + "customer/sendOtp"
            static let emailPhoneValidate         = BaseURL.SecondaryUrl + "emailPhoneValidate"
            static let logout                     = BaseURL.SecondaryUrl + "customer/logout"
            static let refreshToken               = BaseURL.SecondaryUrl + "generateToken"
            static let terms_and_conditions       = BaseURL.SecondaryUrl + "webpagedata"
            static let generateToken              = BaseURL.SecondaryUrl + "generateToken"
            
        }
        
        struct Cart{
            static let cart                    = BaseURL.SecondaryUrl + "cart"
            static let cartNew                 = BaseURL.SecondaryUrl + "cart/new"
            static let carts                   = BaseURL.SecondaryUrl + "carts"
            static let address                 = BaseURL.SecondaryUrl + "ipLocation"
            static let slots                   = BaseURL.SecondaryUrl + "slots"
            static let prescriptions           = BaseURL.SecondaryUrl + "prescriptions"
            static let addCartMultiple         = BaseURL.SecondaryUrl + "nau/bulk/cart"
            static let reasons                 = BaseURL.SecondaryUrl + "reason"
            static let tips                    = BaseURL.SecondaryUrl + "storeCategoySettings"
        }
        
        struct PromoCode{
            static let getCoupon               = BaseURL.PromoCode + "promocode/view"
            static let postCoupon              = BaseURL.PromoCode + "v3/promotion"
        }
        
        struct Order{
            static let order                   = BaseURL.SecondaryUrl + "order"
            static let orders                  = BaseURL.SecondaryUrl + "orders"
            static let orderDetails            = BaseURL.SecondaryUrl + "orders/details"
            static let packageDetails          = BaseURL.SecondaryUrl + "order/package/details"
            static let reOrder                 = BaseURL.SecondaryUrl + "reOrder"
        }
        
        struct HomeTabBar{
            static let home                       = BaseURL.PrimaryUrl + "home/page"
            static let allCategories              = BaseURL.PrimaryUrl + "category/list"//"categoryList/"
            static let suggestions                = BaseURL.PrimaryUrl + "suggestions"
            static let searchFilter               = BaseURL.PrimaryUrl + "searchFilter"
            static let recentSearch               = BaseURL.PrimaryUrl + "recent/search"
            static let filterParameters           = BaseURL.PrimaryUrl + "filter"
            static let subCategoryProducts        = BaseURL.PrimaryUrl + "subCategoryProducts/"
            static let subCategoryList            = BaseURL.PrimaryUrl + "subCategoryList"
            static let offerProducts              = BaseURL.PrimaryUrl + "offer/products"
            static let recentViews                = BaseURL.PrimaryUrl + "user/recentview"
            static let notify                     = BaseURL.PrimaryUrl + "product/notify"
            static let shoppinglist               = BaseURL.PrimaryUrl + "shopping/list"
            static let getUserlists               = BaseURL.PrimaryUrl + "user/shopping/list"
            static let allShoppingListProducts    = BaseURL.PrimaryUrl + "shopping/list/products"
            static let updateShopingList          = BaseURL.PrimaryUrl + "product/shopping/list"
            static let symptomsList               = BaseURL.PrimaryUrl + "symptoms/list"
            static let bookmark                   = BaseURL.SecondaryUrl + "bookmark"
            static let brandList                  = BaseURL.PrimaryUrl + "brand/list"
        }
        
        struct Product{
            static let details                    = BaseURL.PrimaryUrl + "product/details"
            static let addFavourite               = BaseURL.PrimaryUrl + "favourite/product/"
            static let removeFavourite            = BaseURL.PrimaryUrl + "removeFavouriteProduct/"
            static let allReviews                 = BaseURL.PrimaryUrl + "product/review"
            static let getratingAttributes        = BaseURL.PrimaryUrl + "ratableAttribute"
            static let productReviewRating        = BaseURL.PrimaryUrl + "productReviewRating/"
            static let like_dislike               = BaseURL.PrimaryUrl + "likeDislikeReview/"
            static let reportReview               = BaseURL.PrimaryUrl + "reportReview/"
            static let getSellers                 = BaseURL.PrimaryUrl + "seller/list"
            static let qrScanner                  = BaseURL.PrimaryUrl + "scan/products"
            static let productListFromIds         = BaseURL.PrimaryUrl + "product/list"
            
        }
        
        struct Profile {
            static let whisList                   = BaseURL.PrimaryUrl + "wishList/"
            static let Profile                    = BaseURL.SecondaryUrl + "customer/profile"
            static let languages                  = BaseURL.SecondaryUrl + "utility/languages"
            static let faqs                       = BaseURL.SecondaryUrl + "customer/support"
            static let address                    = BaseURL.SecondaryUrl + "address"
            static let makeDefault                = BaseURL.SecondaryUrl + "defaultAddress"
            static let changeEmail                = BaseURL.SecondaryUrl + "customer/emPatchSend"
            static let verifyChanges              = BaseURL.SecondaryUrl + "customer/emPatchVerify"
            static let notification               = BaseURL.PrimaryUrl + "user/notification"
        }
        
        struct Payment{
            static let walletTransactions         = BaseURL.SecondaryUrl + "walletTransaction"
            static let wallet                     = BaseURL.SecondaryUrl + "wallet"
            static let card                       = BaseURL.stripe + "customer"
            static let deleteCard                 = BaseURL.stripe + "paymentMethod"
            static let intentApi                  = BaseURL.stripe + "setupIntent"
            static let walletRecharge             = BaseURL.SecondaryUrl + "wallet/recharge"
            static let estimateCurrency           = BaseURL.SecondaryUrl + "walletTransaction/estimate"
        }
    }
    
    struct ParameterConstants {
        static let value                    = "value"
        static let unit                     = "unit"
        static let reduced_amt              = "reduced_amt"
        static let price                    = "price"
        static let products                 = "products"
        static let admin                    = "admin"
        static let appName                  = "appName"
        static let action                   = "action"
        static let amount                   = "amount"
        static let sortType                 = "sortType"
        static let accessToken              = "accessToken"
        static let attributeId              = "attributeId"
        static let authorization            = "authorization"
        static let billingAddressId         = "billingAddressId"
        static let platform                 = "platform"
        static let currencysymbol           = "currencysymbol"
        static let currencyCode             = "currencycode"
        static let currency                 = "currency"
        static let centralProductId         = "centralProductId"
        static let customerType             = "customerType"
        static let otpCode                  = "otpCode"
        static let otpId                    = "otpId"
        static let fromCurrency             = "fromCurrency"
        static let toCurrency               = "toCurrency"
        static let newPassword              = "newPassword"
        static let oldPassword              = "oldPassword"
        static let requesttype              = "requesttype"
        static let storeType                = "storeType"
        static let pageState                = "pageState"
        static let orderType                = "orderType"
        static let signUpType               = "signUpType"
        static let userType                 = "userType"
        static let userLogedIn              = "userLogedIn"
        static let triggeredBy              = "triggeredBy"
        static let type                     = "type"
        static let language                 = "language"
        static let filterType               = "filterType"
        static let folder                   = "folder"
        static let file                     = "file"
        static let popularStatus            = "popularStatus"
        static let resetType                = "resetType"
        static let productId                = "productId"
        static let packageId                = "packageId"
        static let productOrderId           = "productOrderId"
        static let parentProductId          = "parentProductId"
        static let categoryId               = "categoryId"
        static let cartId                   = "cartId"
        static let coupon                   = "coupon"
        static let payByWallet              = "payByWallet"
        static let searchItem               = "searchItem"
        static let subCategoryId            = "subCategoryId"
        static let search                   = "search"
        static let loginType                = "logintype"
        static let name                     = "name"
        static let desc                     = "desc"
        static let discount                 = "discount"
        static let link                     = "link"
        static let userPassword             = "userPassword"
        static let firstName                = "firstName"
        static let fetchSize                = "fetchSize"
        static let facebookId               = "facebookId"
        static let googleId                 = "googleId"
        static let mobile                   = "mobile"
        static let email                    = "email"
        static let profilePic               = "profilePic"
        static let profilePicture           = "profilePicture"
        static let ipAddress                = "ipAddress"
        static let ipaddress                = "ipaddress"
        static let images                   = "images"
        static let publicIp                 = "ipaddress"
        static let paymentType              = "paymentType"
        static let storeCategoryId          = "storeCategoryId"
        static let userId                   = "userId"
        static let mobileNumber             = "mobileNumber"
        static let mobileNumberCode         = "mobileNumberCode"
        static let locality                 = "locality"
        static let addLine1                 = "addLine1"
        static let landmark                 = "landmark"
        static let city                     = "city"
        static let state                    = "state"
        static let orderTime                = "orderTime"
        static let orderBy                  = "orderBy"
        static let country                  = "country"
        static let offers                   = "offers"
        static let placeId                  = "placeId"
        static let pincode                  = "pincode"
        static let latitude                 = "latitude"
        static let longitude                = "longitude"
        static let taggedAs                 = "taggedAs"
        static let addressId                = "addressId"
        static let cityid                   = "cityid"
        static let cardId                   = "cardId"
        static let countryid                = "countryid"
        static let newQuantity              = "newQuantity"
        static let productid                = "productid"
        static let paymentMethod            = "paymentMethod"
        static let limit                    = "limit"
        static let reviewDescription        = "reviewDescription"
        static let reviewTitle              = "reviewTitle"
        static let reviewType               = "reviewType"
        static let rating                   = "rating"
        static let reason                   = "reason"
        static let comment                  = "comment"
        static let walletId                 = "walletId"
        static let walletData               = "walletData"
        static let reviewId                 = "reviewId"
        static let sellerId                 = "sellerId"
        static let sellerReview             = "sellerReview"
        static let status                   = "status"
        static let txnType                  = "txnType"
        static let timeFilter               = "timeFilter"
        static let like                     = "like"
        static let dislike                  = "dislike"
        static let refreshToken             = "refToken"
        static let isGuestLogIn             = "GuestUser"
        static let lat                      = "lat"
        static let orderId                  = "orderId"
        static let lon                      = "long"
        static let unitId                   = "unitId"
        static let zoneId                   = "zoneId"
        static let qrcode                   = "qrcode"
        static let quantity                 = "quantity"
        static let uploadTo                 = "uploadTo"
        static let cartType                 = "cartType"
        static let makedefault              = "default"
        static let searchType               = "searchType"
        static let storeTypeId              = "storeTypeId"
        static let storeId                  = "storeId"
        static let sellerData               = "sellerData"
        static let reviewData               = "reviewData"
        static let countryCode              = "countryCode"
        static let verifyType               = "verifyType"
        static let zone                     = "z_id"
        static let Category                 = "Category"
        static let cart_id                  = "cart_id"
        static let currency_details         = "currency_details"
        static let currency_name            = "currency_name"
        static let currency_symbol          = "currency_symbol"
        static let delivery_fee             = "delivery_fee"
        static let email_id                 = "email_id"
        static let payment_method_type      = "payment_method_type"
        static let pickup_state             = "pickup_state"
        static let promo_code               = "promo_code"
        static let region_applied_on        = "region_applied_on"
        static let total_purchase_value     = "total_purchase_value"
        static let user_id                  = "user_id"
        static let wallet_state             = "wallet_state"
        static let product_id               = "product_id"
        static let brandName                = "brandName"
        static let centralproduct_id        = "centralproduct_id"
        static let storecategory_idId       = "storecategory_idId"
        static let product_reduced_amt      = "product_reduced_amt"
        static let reduce_delivery_fee      = "reduce_delivery_fee"
        static let reduce_price             = "reduce_price"
        static let reduce_total_amt         = "reduce_total_amt"
        static let categories               = "categories"
        static let final_unit_price         = "final_unit_price"
        static let unit_price               = "unit_price"
        static let central_product_id       = "central_product_id"
        static let category_id              = "category_id"
        static let taxAmount                = "taxAmount"
        static let unitPrice                = "unitPrice"
        static let tax                      = "tax"
        static let taxValue                 = "taxValue"
        static let taxId                    = "taxId"
        static let taxName                  = "taxName"
        static let totalValue               = "totalValue"
        static let city_id                  = "city_id"
        static let country_id               = "country_id"
        static let promo_id                 = "promo_id"
        static let contactLessDelivery      = "contactLessDelivery"
        static let contactLessDeliveryReason = "contactLessDeliveryReason"
        static let slotId                   = "slotId"
        static let extraNote                = "extraNote"
        
        static let id                       = "id"
        static let image                    = "image"
        static let fore                     = "for"
        static let title                    = "title"
        static let shoppingId               = "shoppingId"
        static let data                     = "data"
        static let from                     = "from"
        static let to                       = "to"
        static let searchIn                 = "searchIn"
        static let orderImages              = "orderImages"
        static let bookmarkId               = "bookmarkId"
        static let userShoppingListId       = "userShoppingListId"
        static let productDataReOrder       = "productDataReOrder"
        static let deliverySlot             = "deliverySlot"
        static let tip                      = "tip"
        static let total_amt                = "total_amt"
        static let store_id                 = "store_id"
        
        //food
        static let ratings                  = "ratings"
        static let avgCost                  = "avgCost"
        static let page                     = "page"
        static let store_Id                 = "s_id"
        static let o_id                     = "o_id"
        static let childProductId           = "childProductId"
        static let storeid                  = "storeid"
        static let bufferTime               = "bufferTime"
        static let date                     = "date"
        static let store_category_id        = "store_category_id"
        static let filter                   = "filter"
        static let containsMeat             = "containsMeat"
        static let attributeName            = "attributeName"
        static let attributeValues          = "attributeValues"
        static let sellerTypeId             = "sellerTypeId"
        static let storeFrontTypeId         = "storeFrontTypeId"
        static let isExpressDelivery        = "isExpressDelivery"
        static let cityId                   = "cityId"
        static let service_type             = "service_type"
        static let countryId                = "countryId"
    }
    
    struct StorageKeys {
        static let userProfileData            = "UserProfileData"
        static let username                   = "Name"
        static let number                     = "Number"
        static let email                      = "Email"
        static let countryCode                = "CountryCode"
        static let userId                     = "UserId"
    }
    
    struct SearchParameters{
        static let query                        = "q"
        static let size                         = "size"
        static let page                         = "page"
        static let from                         = "skip"
        static let searchedText                 = "q"
        static let searchCategory               = "fname"
        static let searchSubCategory            = "sname"
        static let searchSubSubCategory         = "tname"
        static let searchBrand                  = "bname"
        static let colour                       = "colour"
        static let minprice                     = "minprice"
        static let maxprice                     = "maxprice"
        static let facet                        = "facet_"
        static let sort                         = "sort"
        static let offerId                      = "o_id"
        static let loginType                    = "loginType"
        static let symptoms                    = "symptoms"
        static let cuisines                    = "cuisines"
        static let text                        = "text"
    }
    
    
    
}
